## Use an official Node runtime as a parent image
#FROM node:18-alpine as build
#EXPOSE 80
## Set the working directory
#WORKDIR /app
#
## Copy the package.json and package-lock.json files
#COPY Clients/patient-monitoring-client/package*.json ./
#
## Install dependencies
#RUN npm install
#
## Copy the rest of the application code
#COPY Clients/patient-monitoring-client/ .
#
## Build the Angular application
#RUN npm run build
#
## Stage 2 - Serve the Angular application using Nginx
#FROM node:18-alpine
#COPY --from=build /app/dist/patient-monitoring-client /usr/share/nginx/html
#
# Stage 1: Install dependencies and build the Angular app
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY Clients/patient-monitoring-client/package*.json ./

# Install dependencies
RUN npm install

COPY Clients/patient-monitoring-client/ .
# Copy the rest of the application files

# Expose the development port (default for ng serve)
EXPOSE 4200
# Start the Angular application in development mode
CMD  ["npx", "ng", "serve", "--host", "0.0.0.0", "--disable-host-check", "--poll", "2000"]
